no-hosts
no-resolv
log-queries
addn-hosts=/home/jorge/Downloads/NetworksTopology/saltillo/records.txt
except-interface=lo

# VLAN 20 - Engineering (10.30.20.0/25, gw 10.30.20.1)
dhcp-range=set:vlan20,10.30.20.50,10.30.20.120,255.255.255.128,12h
dhcp-option=tag:vlan20,option:router,10.30.20.1
dhcp-option=tag:vlan20,option:dns-server,10.30.130.40

# VLAN 50 - Reception (10.30.50.0/27, gw 10.30.50.1)
dhcp-range=set:vlan50,10.30.50.5,10.30.50.15,255.255.255.224,12h
dhcp-option=tag:vlan50,option:router,10.30.50.1
dhcp-option=tag:vlan50,option:dns-server,10.30.130.40